const GRAPH_WIDTH = 355;
const MAX_PRICE = 1_000_000;
const INPUT_MAX_VALUE = 100;
const ONE_PER_GRAPH_WIDTH = GRAPH_WIDTH / INPUT_MAX_VALUE;
const ONE_PER_PRICE = MAX_PRICE / GRAPH_WIDTH;
const MIN_BETWEEN_RATIO = 5;

export {
  GRAPH_WIDTH,
  MAX_PRICE,
  ONE_PER_GRAPH_WIDTH,
  ONE_PER_PRICE,
  MIN_BETWEEN_RATIO,
};
